name: Release

on:
  push:
    tags: ['v*']

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile add nixpkgs#devenv
      - name: Build release binaries
        run: devenv shell cargo build --release
      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/release/radiod
            target/release/radiod-ctl
